BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "pre-one"
            Button:
                text: "one"
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "two"
            Button:
                text: "three"
            Button:
                text: "four"
    Label:
        size_hint_y: 0.1
        text: "Yilin Li my dear son"